### ISSUE TITLE
Game Muzak

### ISSUE THREAD

**Issue by bjornsen** [nycresistor/Semaphore-Hero#19]
Colleen's Dad is going to make us a slew of 80s inspired tropical jams...or at least something with a tune.

**Comment by widget1985** [comment]
This is copyrighted, but I really like it, and maybe it could be used as inspiration? https://homestuck.bandcamp.com/track/pumpkin-party-in-sea-hitlers-water-apocalypse

**Comment by colleenaf** [comment]
Thanks for the inspiration, Widget. Passed it along to Poppa V who is totally on it! So much so that he broke out the steel drums WHILE we were on the phone. He has since texted me that he's listening to "that Mario stuff" so he gets a feel for how videogame music should work in the background. Should have something by the end of the weekend.

**Comment by colleenaf** [comment]
Poppa V comes though! Super cheesy and campy and I sort of love it. Definitely the kind of song that will make you lose your mind if you listen to it too long, which seems theme appropriate. 

http://furboajerboa.com/assets/mp3/SwingOneTooMix.mp3

**Comment by jqpubliq** [comment]
Your dad is amazing.  This will be great.  And it will be seared into all of our brains for weeks to come!

**Comment by colleenaf** [comment]
He just sent another option that's more steel drum-y. 

Let's consider the above Option1, and this one Option 2: 
http://furboajerboa.com/assets/mp3/InventOneTweeMaster.mp3

Let me know what ya think!

**Comment by phooky** [comment]
oh my god all of this is amazing

**Comment by bjornsen** [comment]
He read my mind! I thought the first one was great for non-gameplay
sections like the title/intro but not upbeat enough for fast-action
flagging. Between the two, we'll be well-covered...though don't let that
suppress his creative output if we wants to keep producing quality island
jams.

And yes, I would totally go mad from listening to these for 10 hours
straight. Awesome!

**Comment by colleenaf** [comment]
I think he's done with island songs since he's already got his eyes on another creative project (remaking old Paul-Simon 80's songs by ear with him doing all the parts/harmonies/instruments. etc) . But I really LOVE Option 2. I leave it entirely up to you game design folk as to how you want to use either or both songs.

And for those who want to hear what I was talking about on Thursday, here's an alternate universe Beatles where Ringo is the star. Still can't believe he did 400+ of these songs all by ear for no real reason in a year: 
FLABBY ROAD: http://furboajerboa.com/assets/mp3/FlabbyRoad/
SGT. POOPERS: http://furboajerboa.com/assets/mp3/SgtPoopers/

Retirement sounds pretty sweet guys.

**Comment by jqpubliq** [comment]
CLOSED AF.

**Comment by colleenaf** [comment]
Dad couldn't leave it alone. He "remastered" Option 2 to make it sound cleaner: 
http://furboajerboa.com/assets/mp3/InventOneTweeFourMaster.mp3

I thanked him like crazy but told him he isn't allowed to keep working on this, because he might continue to fall down a steel drum lined rabbit hole. But I do think this is a slight improvement over the last one if it's easy to swap in.
